services:

  mlflow:
    build: './mlflow'
    ports:
      - "5000:5000"
    container_name: Mlflow
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY_ID=supersecret
      # MLFLOW_SERVER_DEFAULT_ARTIFACT_ROOT: "http://minio:9000/mlflow"
    entrypoint: bash -c "mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root s3://mlflow/ --host 0.0.0.0"


  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    container_name: Minio
    command: server /data --console-address ':9001' --address ':9000'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
    volumes:
      - ./minio:/data